// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrWCvI0DOmHfoAt6E03x2rnu6LuXLBMYs',
    appId: '1:708508179122:web:c4c9c2bab477ab167c87ab',
    messagingSenderId: '708508179122',
    projectId: 'e-book-store-ea70e',
    authDomain: 'e-book-store-ea70e.firebaseapp.com',
    storageBucket: 'e-book-store-ea70e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ntlwzRUtOfD22WdnrgX_dqdrLCvat3s',
    appId: '1:708508179122:android:f69ab036d75e86eb7c87ab',
    messagingSenderId: '708508179122',
    projectId: 'e-book-store-ea70e',
    storageBucket: 'e-book-store-ea70e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDrh0vDgcY-JRuto5ulTvBmCFSruiz9M',
    appId: '1:708508179122:ios:153336e755fe98bc7c87ab',
    messagingSenderId: '708508179122',
    projectId: 'e-book-store-ea70e',
    storageBucket: 'e-book-store-ea70e.appspot.com',
    iosClientId: '708508179122-na2a4l273io7jski1h6pdve3d0krq5f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDrh0vDgcY-JRuto5ulTvBmCFSruiz9M',
    appId: '1:708508179122:ios:350b5e83260987a57c87ab',
    messagingSenderId: '708508179122',
    projectId: 'e-book-store-ea70e',
    storageBucket: 'e-book-store-ea70e.appspot.com',
    iosClientId: '708508179122-kqv7of771r0nmoucpeie9tqlma95edbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}
